# dadjokes service yaml configuration for kubernetes
# exposes NodePort Service with auto assigned nodePort
---
apiVersion: v1
kind: Service
metadata:
  name: dadjokes-service
  labels:
    app: dadjokes
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8100
  selector:
    app: dadjokes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadjokes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dadjokes
  template:
    metadata:
      labels:
        app: dadjokes
    spec:
      containers:
      - image: yesinteractive/dadjokes
        name: dadjokes
        ports:
        - containerPort: 8100
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-dadjokes
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: dadjokes-deployment
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dadjokes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dadjokes.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dadjokes-service
            port:
              number: 80
